# -*- coding: utf-8 -*-
"""Telco customer churn Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17hWgDSDm4HF9bCegwX5As-2rIHzZhUT3
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
color= sns.color_palette("pastel")
sns.set(style="whitegrid", context="talk", font_scale=0.8, palette=color,rc={'figure.figsize':(8,4)})

df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv', index_col="customerID")

df.head()

print(f"There are {len(df.index.unique())} unique customers in {df.shape[0]}")

df.info()

df["TotalCharges"] = df["TotalCharges"].apply(pd.to_numeric, errors='coerce')

df.isna().sum()

df[df['TotalCharges'].isnull()]

df.loc[df['TotalCharges'].isnull(), 'TotalCharges'] = df.loc[df['TotalCharges'].isnull(), 'MonthlyCharges']

plt.figure(figsize=(3,3))
sns.boxplot(df.tenure)
plt.show()

plt.figure(figsize=(3,3))
sns.boxplot(df.MonthlyCharges)
plt.show()

plt.figure(figsize=(3,3))
sns.boxplot(df["TotalCharges"])
plt.show()

for i in df.columns:
  print(f"Column '{i}' has : {df[i].unique()}")

numerical_features = ["tenure", "MonthlyCharges", "TotalCharges"]
categoric_features = ["MultipleLines", "InternetService", "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies", "Contract", "PaymentMethod"]
binary_features = ["gender", "SeniorCitizen", "Partner", "Dependents", "PhoneService", "PaperlessBilling", "Churn"]
data_encoded = pd.get_dummies(df, columns=categoric_features)
data_encoded = pd.get_dummies(data_encoded, columns=binary_features, drop_first=True)

print(f"Data Columns: {len(df.columns)}\nEncoded Data Columns: {len(data_encoded.columns)}")

data_encoded.info()

data_test = data_encoded.copy()

data_encoded["AverageCharges"] =  data_encoded["TotalCharges"] / data_encoded["tenure"]
data_encoded.loc[data_encoded["tenure"] == 0, "AverageCharges"] = data_encoded["TotalCharges"]

data_encoded["AboveAverageCharges"] = (data_encoded["MonthlyCharges"] > data_encoded["AverageCharges"].mean()).astype(int)

data_encoded["AboveAverageCharges"].value_counts()

data_encoded.mean()

columns_to_delete = [
                    'OnlineSecurity_No internet service',
                    'OnlineBackup_No internet service',
                    'DeviceProtection_No internet service',
                    'TechSupport_No internet service',
                    'StreamingTV_No internet service',
                    'StreamingMovies_No internet service']
data_encoded.drop(columns=columns_to_delete, inplace=True)
print(f"Number of Columns: {len(data_encoded.columns)}")

services = [
    'MultipleLines_Yes',
    'InternetService_DSL',
    'InternetService_Fiber optic',
    'OnlineSecurity_Yes',
    'OnlineBackup_Yes',
    'DeviceProtection_Yes',
    'TechSupport_Yes',
    'StreamingTV_Yes',
    'StreamingMovies_Yes',
    'PhoneService_Yes',
    'PaperlessBilling_Yes']

data_encoded['ServicesMost'] = data_encoded[services].mean(axis=1)

data_encoded.ServicesMost.value_counts(ascending=True)

data_encoded.columns

columns_to_keep = ['tenure', 'MonthlyCharges', 'TotalCharges', 'MultipleLines_Yes',
                     'InternetService_DSL', 'InternetService_Fiber optic', 'OnlineSecurity_Yes',
                     'OnlineBackup_Yes', 'DeviceProtection_Yes', 'TechSupport_Yes', 'StreamingTV_Yes',
                     'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year',
                     'Contract_Two year', 'PaymentMethod_Bank transfer (automatic)',
                     'PaymentMethod_Credit card (automatic)', 'InternetService_No',
                     'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check',
                     'gender_Male', 'SeniorCitizen_1', 'Partner_Yes', 'Dependents_Yes',
                     'PhoneService_Yes', 'PaperlessBilling_Yes', 'Churn_Yes',
                     'AverageCharges', 'AboveAverageCharges', 'ServicesMost']

data_encoded = data_encoded[columns_to_keep]

print(f"Total Columns Left: {data_encoded.shape[1]}")

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_data = data_encoded.drop("Churn_Yes", axis=1)
scaled_data = scaler.fit_transform(data_encoded)

costs = []
silhouette_scores = []

for i in range(2, 10):
    kmeans = KMeans(n_clusters=i, random_state=0, n_init="auto").fit(scaled_data)
    costs.append(kmeans.inertia_)

    silhouette_avg = silhouette_score(scaled_data, kmeans.labels_)
    silhouette_scores.append(silhouette_avg)

plt.figure(figsize=(10, 3))

plt.subplot(1, 2, 1)
plt.plot(range(2, 10), costs, marker='o')
plt.title('Cost')

plt.subplot(1, 2, 2)
plt.plot(range(2, 10), silhouette_scores, marker='o')
plt.title('Silhouette Score')
plt.show()

km = KMeans(n_clusters=5, n_init=5, verbose=0, random_state=0)
km.fit_predict(scaled_data)
data_encoded["cluster"] = km.labels_

data_encoded.describe()

numerical = ['tenure', 'MonthlyCharges', 'TotalCharges',
             'AverageCharges', 'AboveAverageCharges', 'ServicesMost', 'Churn_Yes']

services = ['MultipleLines_Yes', 'InternetService_DSL', 'InternetService_Fiber optic', 'OnlineSecurity_Yes',
            'OnlineBackup_Yes', 'DeviceProtection_Yes','TechSupport_Yes', 'StreamingTV_Yes',
            'StreamingMovies_Yes', 'InternetService_No', 'PhoneService_Yes', 'PaperlessBilling_Yes', 'ServicesMost', 'Churn_Yes']

demographic = ['gender_Male', 'SeniorCitizen_1', 'Partner_Yes', 'Dependents_Yes', 'Churn_Yes', 'cluster']

other = ['Contract_Month-to-month', 'Contract_One year', 'Contract_Two year',
       'PaymentMethod_Bank transfer (automatic)', 'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check', 'Churn_Yes']

correlation_matrix_all = data_encoded.corr()
abs(correlation_matrix_all).mean()

correlation_matrix_num = data_encoded[numerical].corr()
abs(correlation_matrix_num).mean()

correlation_matrix_serv = data_encoded[services].corr()
abs(correlation_matrix_serv).mean()

correlation_matrix_demo = data_encoded[demographic].corr()
abs(correlation_matrix_demo).mean()

correlation_matrix_other = data_encoded[other].corr()
abs(correlation_matrix_other).mean()

mask = (np.abs(correlation_matrix_all) < 0.5)
plt.figure(figsize=(8, 8))
sns.heatmap(correlation_matrix_all, mask=mask)
plt.show()

mask = (np.abs(correlation_matrix_num) < 0.5)
plt.figure(figsize=(4, 4))
sns.heatmap(correlation_matrix_num, mask=mask)
plt.show()

mask = (np.abs(correlation_matrix_serv) < 0.5)
plt.figure(figsize=(6, 6))
sns.heatmap(correlation_matrix_serv, mask=mask)
plt.show()

mask = (np.abs(correlation_matrix_demo) < 0.3)
plt.figure(figsize=(3, 3))
sns.heatmap(correlation_matrix_demo, mask=mask)
plt.show()

mask = (np.abs(correlation_matrix_other) < 0.4)
plt.figure(figsize=(4, 4))
sns.heatmap(correlation_matrix_other, mask=mask)
plt.show()

plt.figure(figsize=(20,9))
for i, column in enumerate(data_encoded[demographic]):
    plt.subplot(2, 3, i+1)
    sns.countplot(data=data_encoded[demographic], x=column, hue="Churn_Yes")
    for p in plt.gca().patches:
        plt.text(p.get_x() + p.get_width() / 2., p.get_height(), '%d' % int(p.get_height()), ha='center')
plt.show()

plt.figure(figsize=(25,25))
for i, column in enumerate(data_encoded[services]):
    plt.subplot(5, 3, i+1)
    sns.countplot(data=data_encoded[services], x=column, hue="Churn_Yes")
    for p in plt.gca().patches:
        plt.text(p.get_x() + p.get_width() / 2., p.get_height(), '%d' % int(p.get_height()), ha='center')
plt.show()

plt.figure(figsize=(20,13))
for i, column in enumerate(data_encoded[other]):
    plt.subplot(3, 3, i+1)
    sns.countplot(data=data_encoded[other], x=column, hue="Churn_Yes")
    for p in plt.gca().patches:
        plt.text(p.get_x() + p.get_width() / 2., p.get_height(), '%d' % int(p.get_height()), ha='center')
plt.show()

plt.figure(figsize=(25,15))
for i, column in enumerate(data_encoded[numerical]):
    plt.subplot(3, 3, i+1)
    sns.kdeplot(data=data_encoded[numerical], x=column, fill=True, hue="Churn_Yes", warn_singular=False)
plt.show()

sns.lineplot(data=data_encoded, x="tenure", y="MonthlyCharges")
plt.show()

